<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260728140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Agency bookings, tickets and VP reference sequence';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE `agency_booking` (AB_ID VARCHAR(16) NOT NULL, AB_PASSENGER_NAME VARCHAR(120) NOT NULL, AB_PASSENGER_ID VARCHAR(60) NOT NULL, AB_PASSENGER_PHONE VARCHAR(20) NOT NULL, AB_SEAT_NUMBER VARCHAR(10) NOT NULL, AB_TRAVEL_DATE DATE NOT NULL, AB_STATUS VARCHAR(12) NOT NULL, AB_OKAPI_PASS_REF VARCHAR(40) DEFAULT NULL, AB_CREATED_AT DATETIME NOT NULL, AB_UPDATED_AT DATETIME DEFAULT NULL, AB_AGENCY VARCHAR(16) NOT NULL, AB_OFFER VARCHAR(16) NOT NULL, INDEX IDX_AGENCY_BOOKING_AGENCY (AB_AGENCY), INDEX IDX_AGENCY_BOOKING_OFFER (AB_OFFER), INDEX IDX_AGENCY_BOOKING_OCCUPANCY (AB_OFFER, AB_TRAVEL_DATE, AB_STATUS), PRIMARY KEY(AB_ID)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE `agency_ticket` (AK_ID VARCHAR(16) NOT NULL, AK_REFERENCE VARCHAR(20) NOT NULL, AK_PASSENGER_NAME VARCHAR(120) NOT NULL, AK_PASSENGER_ID VARCHAR(60) NOT NULL, AK_PASSENGER_PHONE VARCHAR(20) NOT NULL, AK_SEAT_NUMBER VARCHAR(10) NOT NULL, AK_TRAVEL_DATE DATE NOT NULL, AK_TICKET_PRICE INT NOT NULL, AK_PASS_PRICE INT NOT NULL, AK_CURRENCY VARCHAR(3) NOT NULL, AK_STATUS VARCHAR(12) NOT NULL, AK_OKAPI_PASS_REF VARCHAR(40) DEFAULT NULL, AK_HAS_EXISTING_PASS TINYINT(1) NOT NULL, AK_NOTES LONGTEXT DEFAULT NULL, AK_QR_PAYLOAD LONGTEXT DEFAULT NULL, AK_CREATED_AT DATETIME NOT NULL, AK_UPDATED_AT DATETIME DEFAULT NULL, AK_AGENCY VARCHAR(16) NOT NULL, AK_BOOKING VARCHAR(16) DEFAULT NULL, AK_OFFER VARCHAR(16) NOT NULL, UNIQUE INDEX UNIQ_AGENCY_TICKET_REFERENCE (AK_REFERENCE), UNIQUE INDEX UNIQ_AGENCY_TICKET_BOOKING (AK_BOOKING), INDEX IDX_AGENCY_TICKET_AGENCY (AK_AGENCY), INDEX IDX_AGENCY_TICKET_OFFER (AK_OFFER), INDEX IDX_AGENCY_TICKET_OCCUPANCY (AK_OFFER, AK_TRAVEL_DATE, AK_STATUS), PRIMARY KEY(AK_ID)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE `agency_ticket_sequence` (AS_ID VARCHAR(16) NOT NULL, AS_YEAR INT NOT NULL, AS_LAST_NUMBER INT NOT NULL, AS_AGENCY VARCHAR(16) NOT NULL, UNIQUE INDEX UNIQ_AGENCY_TICKET_SEQ (AS_AGENCY, AS_YEAR), INDEX IDX_AGENCY_TICKET_SEQ_AGENCY (AS_AGENCY), PRIMARY KEY(AS_ID)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE `agency_booking` ADD CONSTRAINT FK_AGENCY_BOOKING_AGENCY FOREIGN KEY (AB_AGENCY) REFERENCES `agency` (AG_ID)');
        $this->addSql('ALTER TABLE `agency_booking` ADD CONSTRAINT FK_AGENCY_BOOKING_OFFER FOREIGN KEY (AB_OFFER) REFERENCES `agency_offer` (AO_ID)');
        $this->addSql('ALTER TABLE `agency_ticket` ADD CONSTRAINT FK_AGENCY_TICKET_AGENCY FOREIGN KEY (AK_AGENCY) REFERENCES `agency` (AG_ID)');
        $this->addSql('ALTER TABLE `agency_ticket` ADD CONSTRAINT FK_AGENCY_TICKET_BOOKING FOREIGN KEY (AK_BOOKING) REFERENCES `agency_booking` (AB_ID)');
        $this->addSql('ALTER TABLE `agency_ticket` ADD CONSTRAINT FK_AGENCY_TICKET_OFFER FOREIGN KEY (AK_OFFER) REFERENCES `agency_offer` (AO_ID)');
        $this->addSql('ALTER TABLE `agency_ticket_sequence` ADD CONSTRAINT FK_AGENCY_TICKET_SEQ_AGENCY FOREIGN KEY (AS_AGENCY) REFERENCES `agency` (AG_ID)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE `agency_ticket` DROP FOREIGN KEY FK_AGENCY_TICKET_AGENCY');
        $this->addSql('ALTER TABLE `agency_ticket` DROP FOREIGN KEY FK_AGENCY_TICKET_BOOKING');
        $this->addSql('ALTER TABLE `agency_ticket` DROP FOREIGN KEY FK_AGENCY_TICKET_OFFER');
        $this->addSql('ALTER TABLE `agency_booking` DROP FOREIGN KEY FK_AGENCY_BOOKING_AGENCY');
        $this->addSql('ALTER TABLE `agency_booking` DROP FOREIGN KEY FK_AGENCY_BOOKING_OFFER');
        $this->addSql('ALTER TABLE `agency_ticket_sequence` DROP FOREIGN KEY FK_AGENCY_TICKET_SEQ_AGENCY');
        $this->addSql('DROP TABLE `agency_ticket`');
        $this->addSql('DROP TABLE `agency_booking`');
        $this->addSql('DROP TABLE `agency_ticket_sequence`');
    }
}
