<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260311145156 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE `payment` (PA_ID VARCHAR(16) NOT NULL, PA_REFERENCE VARCHAR(80) NOT NULL, PA_AMOUNT NUMERIC(17, 2) NOT NULL, PA_CURRENCY VARCHAR(3) NOT NULL, PA_METHOD VARCHAR(30) NOT NULL, PA_STATUS VARCHAR(10) NOT NULL, PA_PAID_AT DATETIME DEFAULT NULL, PA_CREATED_AT DATETIME NOT NULL, PA_TICKET VARCHAR(16) NOT NULL, PA_PAID_BY VARCHAR(16) DEFAULT NULL, INDEX IDX_6D28840D726BC573 (PA_TICKET), INDEX IDX_6D28840DE2D7066 (PA_PAID_BY), UNIQUE INDEX UNIQ_PAYMENT_REFERENCE (PA_REFERENCE), PRIMARY KEY (PA_ID)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE `ticket` (TI_ID VARCHAR(16) NOT NULL, TI_DISPLAY_NAME VARCHAR(120) DEFAULT NULL, TI_PHONE VARCHAR(15) DEFAULT NULL, TI_IDENTIFIER VARCHAR(255) DEFAULT NULL, TI_STATUS VARCHAR(10) NOT NULL, TI_ISSUED_AT DATETIME NOT NULL, TI_UNIQUE_REFERENCE VARCHAR(8) DEFAULT NULL, TI_VALIDATED_AT DATETIME DEFAULT NULL, TI_GOPASS VARCHAR(16) NOT NULL, TI_DEPARTURE VARCHAR(16) NOT NULL, TI_ARRIVAL VARCHAR(16) NOT NULL, TI_ISSUED_BY VARCHAR(16) DEFAULT NULL, INDEX IDX_97A0ADA33BA7578C (TI_GOPASS), INDEX IDX_97A0ADA346909183 (TI_DEPARTURE), INDEX IDX_97A0ADA3548E67A2 (TI_ARRIVAL), INDEX IDX_97A0ADA37529C3AD (TI_ISSUED_BY), UNIQUE INDEX UNIQ_TICKET_UNIQUE_REFERENCE (TI_UNIQUE_REFERENCE), PRIMARY KEY (TI_ID)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE `payment` ADD CONSTRAINT FK_6D28840D726BC573 FOREIGN KEY (PA_TICKET) REFERENCES `ticket` (TI_ID)');
        $this->addSql('ALTER TABLE `payment` ADD CONSTRAINT FK_6D28840DE2D7066 FOREIGN KEY (PA_PAID_BY) REFERENCES `user` (US_ID)');
        $this->addSql('ALTER TABLE `ticket` ADD CONSTRAINT FK_97A0ADA33BA7578C FOREIGN KEY (TI_GOPASS) REFERENCES `gopass` (GP_ID)');
        $this->addSql('ALTER TABLE `ticket` ADD CONSTRAINT FK_97A0ADA346909183 FOREIGN KEY (TI_DEPARTURE) REFERENCES `checkpoint` (CP_ID)');
        $this->addSql('ALTER TABLE `ticket` ADD CONSTRAINT FK_97A0ADA3548E67A2 FOREIGN KEY (TI_ARRIVAL) REFERENCES `checkpoint` (CP_ID)');
        $this->addSql('ALTER TABLE `ticket` ADD CONSTRAINT FK_97A0ADA37529C3AD FOREIGN KEY (TI_ISSUED_BY) REFERENCES `user` (US_ID)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE `payment` DROP FOREIGN KEY FK_6D28840D726BC573');
        $this->addSql('ALTER TABLE `payment` DROP FOREIGN KEY FK_6D28840DE2D7066');
        $this->addSql('ALTER TABLE `ticket` DROP FOREIGN KEY FK_97A0ADA33BA7578C');
        $this->addSql('ALTER TABLE `ticket` DROP FOREIGN KEY FK_97A0ADA346909183');
        $this->addSql('ALTER TABLE `ticket` DROP FOREIGN KEY FK_97A0ADA3548E67A2');
        $this->addSql('ALTER TABLE `ticket` DROP FOREIGN KEY FK_97A0ADA37529C3AD');
        $this->addSql('DROP TABLE `payment`');
        $this->addSql('DROP TABLE `ticket`');
    }
}
